### ISSUE TITLE
why call sc.DB.Close() after sc.DB.Exec(sqlStr)  in sphinxql.go ？

### ISSUE THREAD

**Issue by tangr206** [yunge/sphinx#13]
http://golang.org/src/database/sql/sql.go ： 
   437	// The returned DB is safe for concurrent use by multiple goroutines
   438	// and maintains its own pool of idle connections. Thus, the Open
   439	// function should be called just once. It is rarely necessary to
   440	// close a DB.

**Comment by yunge** [comment]
Well, this lib began very early(before I published it), the stdlib of Golang was not stable at that time, it's just some kind of defensive code.

**Comment by tangr206** [comment]
ok, but once you close DB, this SphinxClient will nerver get a chance to initial a new connection.  
So maybe you can update your code? do not defer close db?

**Comment by tangr206** [comment]
"nerver get a chance to initial a new connection"  cauz DB is not setted nil, so the second Execute will return "database is closed"

**Comment by yunge** [comment]
I'm not using golang and mysql now, could you kindly help to fix it? thanks.

**Comment by tangr206** [comment]
sure, glad to

**Comment by yunge** [comment]
Thanks for your help!
